"""
Couche d'abstraction base de données.

Renvoie une connexion SQLite (local, développement) OU Postgres (cloud, production)
selon la variable DATABASE_URL définie dans :
  1. st.secrets["DATABASE_URL"]  (Streamlit Cloud)
  2. os.environ["DATABASE_URL"]  (shell/CI)
  3. Rien → fallback SQLite sur le fichier local

Cette abstraction permet à tout le code existant (qui utilise `?` placeholder
et `INSERT OR IGNORE`) de continuer à fonctionner localement sans modification.
Pour Postgres, un wrapper léger traduit la syntaxe SQLite → Postgres à la volée.

Usage identique partout :
    from data.db import get_connection
    conn = get_connection()
    conn.execute("SELECT * FROM fundamentals WHERE ticker = ?", ("SNTS.sn",))
"""

import os
import re
import sqlite3
from typing import Optional

from config import DB_PATH


# ─────────────────────────────────────────────────────────────────
# Détection du type de DB
# ─────────────────────────────────────────────────────────────────

def _get_database_url() -> Optional[str]:
    """Lit DATABASE_URL depuis Streamlit secrets, env var, ou None.
    Normalise `postgres://` → `postgresql://` (psycopg n'accepte que la seconde forme)."""
    url = None
    # 1) Streamlit secrets (si dispo et app streamlit en cours)
    try:
        import streamlit as st
        if hasattr(st, "secrets"):
            try:
                url = st.secrets.get("DATABASE_URL")
            except Exception:
                url = None
    except Exception:
        pass
    # 2) Env var
    if not url:
        url = os.environ.get("DATABASE_URL")
    # Normalisation
    if url and url.startswith("postgres://"):
        url = url.replace("postgres://", "postgresql://", 1)
    return url


def get_db_type() -> str:
    """Retourne 'sqlite' ou 'postgres'."""
    url = _get_database_url()
    if url and url.startswith("postgresql://"):
        return "postgres"
    return "sqlite"


def is_postgres() -> bool:
    return get_db_type() == "postgres"


# ─────────────────────────────────────────────────────────────────
# Wrapper Postgres (compatible sqlite3.Connection)
# ─────────────────────────────────────────────────────────────────

# Mapping syntaxe SQLite → Postgres
_SQLITE_TO_PG_PATTERNS = [
    # INSERT OR IGNORE → INSERT ... ON CONFLICT DO NOTHING
    (re.compile(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", re.IGNORECASE), "INSERT INTO"),
    # INSERT OR REPLACE → INSERT ON CONFLICT DO UPDATE (plus complexe, on lève pour être safe)
    # AUTOINCREMENT → GENERATED BY DEFAULT AS IDENTITY
    (re.compile(r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b", re.IGNORECASE),
     "SERIAL PRIMARY KEY"),
    # CURRENT_TIMESTAMP (ok dans les deux) — pas de changement
    # TIMESTAMP DEFAULT CURRENT_TIMESTAMP (compatible)
    # date('now') → CURRENT_DATE
    (re.compile(r"date\('now'\)", re.IGNORECASE), "CURRENT_DATE"),
    (re.compile(r"datetime\('now'\)", re.IGNORECASE), "CURRENT_TIMESTAMP"),
    # substr → SUBSTRING (les deux marchent dans PG mais uniformisons)
    # PRAGMA journal_mode=WAL → no-op sur PG
]


def _translate_query(query: str) -> str:
    """Traduit les motifs SQLite-only vers Postgres."""
    for pattern, replacement in _SQLITE_TO_PG_PATTERNS:
        query = pattern.sub(replacement, query)
    # Placeholder: ? → %s (psycopg utilise %s par défaut)
    # Attention à ne pas toucher les ? dans les strings. Approche naïve :
    # compter les ? hors des quotes.
    query = _replace_placeholders(query)
    # INSERT OR IGNORE : après le SUB ci-dessus, on a "INSERT INTO" — il faut
    # ajouter ON CONFLICT DO NOTHING si c'était un OR IGNORE. On repère par
    # un flag laissé dans le code appelant OU on détecte si le query original
    # contenait OR IGNORE (déjà traité).
    return query


def _replace_placeholders(query: str) -> str:
    """Remplace `?` par `%s` hors des strings littérales."""
    out = []
    in_single = False
    in_double = False
    i = 0
    while i < len(query):
        ch = query[i]
        if ch == "'" and not in_double:
            in_single = not in_single
        elif ch == '"' and not in_single:
            in_double = not in_double
        elif ch == "?" and not in_single and not in_double:
            out.append("%s")
            i += 1
            continue
        out.append(ch)
        i += 1
    return "".join(out)


class _PostgresCursor:
    """Wrapper cursor psycopg → API compatible sqlite3.Cursor.
    Délègue les attributs manquants au cursor sous-jacent (pour pandas, etc.)."""

    def __init__(self, cursor, had_ignore: bool = False):
        self._cur = cursor
        self._had_ignore = had_ignore

    def fetchone(self):
        return self._cur.fetchone()

    def fetchall(self):
        return self._cur.fetchall()

    def fetchmany(self, size=None):
        if size is None:
            return self._cur.fetchmany()
        return self._cur.fetchmany(size)

    def execute(self, query, params=None):
        # Support pour pandas qui appelle cursor.execute() directement
        from data.db import _translate_query, _PostgresWrapper
        translated = _translate_query(query)
        self._cur.execute(translated, params or ())
        return self

    def executemany(self, query, params_list):
        from data.db import _translate_query
        translated = _translate_query(query)
        return self._cur.executemany(translated, params_list)

    def __iter__(self):
        return iter(self._cur)

    @property
    def description(self):
        return self._cur.description

    @property
    def rowcount(self):
        return self._cur.rowcount

    @property
    def lastrowid(self):
        return None

    @property
    def arraysize(self):
        return getattr(self._cur, "arraysize", 1)

    def close(self):
        self._cur.close()

    def __getattr__(self, name):
        # Fallback : déléguer au cursor sous-jacent pour tout attribut manquant
        return getattr(self._cur, name)


class _PostgresWrapper:
    """Wrapper psycopg.Connection → API compatible sqlite3.Connection."""

    def __init__(self, conn):
        self._conn = conn

    def _run(self, query: str, params=None):
        # Traduction SQLite → Postgres
        translated = _translate_query(query)
        had_ignore = "INSERT OR IGNORE" in query.upper()
        if had_ignore:
            if "ON CONFLICT" not in translated.upper():
                translated = translated.rstrip(" ;") + " ON CONFLICT DO NOTHING"

        # PRAGMA table_info(t) → SELECT sur information_schema (émule SQLite)
        use_tuple_row = False
        m = re.match(r"\s*PRAGMA\s+table_info\s*\(\s*(\w+)\s*\)\s*;?\s*$",
                     translated, re.IGNORECASE)
        if m:
            table = m.group(1)
            translated = (
                "SELECT ordinal_position AS cid, column_name AS name, "
                "data_type AS type, "
                "CASE WHEN is_nullable='NO' THEN 1 ELSE 0 END AS notnull, "
                "column_default AS dflt_value, 0 AS pk "
                "FROM information_schema.columns "
                f"WHERE table_name = '{table}' ORDER BY ordinal_position"
            )
            params = None
            use_tuple_row = True  # SQLite PRAGMA renvoie des tuples, pas des dicts

        if use_tuple_row:
            from psycopg.rows import tuple_row
            cur = self._conn.cursor(row_factory=tuple_row)
        else:
            cur = self._conn.cursor()
        cur.execute(translated, params or ())
        return _PostgresCursor(cur, had_ignore=had_ignore)

    def execute(self, query: str, params=None):
        return self._run(query, params)

    def executescript(self, script: str):
        """SQLite's executescript exécute plusieurs statements séparés par `;`.
        En Postgres, on split et exécute chacun."""
        translated = _translate_query(script)
        # Simple split sur `;` — suffisant pour init_db
        for stmt in translated.split(";"):
            stmt = stmt.strip()
            if stmt:
                cur = self._conn.cursor()
                cur.execute(stmt)
                cur.close()

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()

    def cursor(self):
        return _PostgresCursor(self._conn.cursor())


# ─────────────────────────────────────────────────────────────────
# Point d'entrée principal
# ─────────────────────────────────────────────────────────────────

def get_connection():
    """Retourne une connexion SQLite ou Postgres.
    Interface identique côté appelant (execute, fetchone, commit, close)."""
    if is_postgres():
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as e:
            raise ImportError(
                "DATABASE_URL pointe vers Postgres mais psycopg n'est pas installé. "
                "Lancer : pip install 'psycopg[binary]'"
            ) from e
        url = _get_database_url()
        conn = psycopg.connect(url, row_factory=dict_row, autocommit=False)
        return _PostgresWrapper(conn)

    # SQLite (défaut)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    return conn


def current_user_id() -> str:
    """Retourne l'identifiant (email) de l'utilisateur connecté.

    - Mode local (pas d'auth) : 'local'
    - Streamlit avec st.user (auth Google OAuth, v1.42+) : renvoie l'email
    - Si une clé 'user_id' est définie dans st.session_state (par ex. lors d'un
      changement de compte), elle est prioritaire.
    """
    try:
        import streamlit as st
        # Priorité : session_state override (utile pour tests/admin)
        override = st.session_state.get("user_id_override") if hasattr(st, "session_state") else None
        if override:
            return override
        user = getattr(st, "user", None)
        if user is not None:
            is_logged = getattr(user, "is_logged_in", False)
            if is_logged:
                email = getattr(user, "email", None)
                if email:
                    return email
    except Exception:
        pass
    return "local"


def read_sql_df(query: str, params=None, parse_dates=None):
    """Exécute une SELECT et renvoie un DataFrame — compatible SQLite + Postgres.
    Remplace `pd.read_sql_query(sql, conn)` qui ne supporte pas nos wrappers Postgres."""
    import pandas as pd
    conn = get_connection()
    try:
        cur = conn.execute(query, params or ())
        rows = cur.fetchall()
        # Récupérer les noms de colonnes
        description = None
        if hasattr(cur, "description") and cur.description:
            description = [d[0] for d in cur.description]
        # Convertir rows en liste de tuples/dict pour pandas
        if rows and isinstance(rows[0], dict):
            df = pd.DataFrame(rows)
        elif description:
            df = pd.DataFrame(rows, columns=description)
        else:
            df = pd.DataFrame(rows)
        # Parse dates
        if parse_dates:
            for col in parse_dates:
                if col in df.columns:
                    df[col] = pd.to_datetime(df[col], errors="coerce")
        return df
    finally:
        conn.close()


def db_info() -> dict:
    """Infos utiles pour debug / UI."""
    db_type = get_db_type()
    info = {"type": db_type}
    if db_type == "sqlite":
        info["path"] = DB_PATH
        info["exists"] = os.path.exists(DB_PATH)
        if info["exists"]:
            info["size_mb"] = round(os.path.getsize(DB_PATH) / 1024 / 1024, 2)
    else:
        url = _get_database_url() or ""
        # Masquer le mot de passe
        import re as _re
        safe = _re.sub(r"://[^:]+:[^@]+@", "://***:***@", url)
        info["url"] = safe
    return info
